In [2]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [ ]:
df.head()
df[df["entity"].str.contains("k", regex=True)] 
#Filtro con expresiones regulares

             entity code  year  life_expectancy_0
2795   Burkina Faso  BFA  1950            33.0262
2796   Burkina Faso  BFA  1951            33.3732
2797   Burkina Faso  BFA  1952            33.6027
2798   Burkina Faso  BFA  1953            33.8987
2799   Burkina Faso  BFA  1954            34.1847
...             ...  ...   ...                ...
20808    Uzbekistan  UZB  2019            72.0934
20809    Uzbekistan  UZB  2020            71.4613
20810    Uzbekistan  UZB  2021            71.6808
20811    Uzbekistan  UZB  2022            72.1465
20812    Uzbekistan  UZB  2023            72.3884

[1337 rows x 4 columns]

In [9]:
df.columns.to_list()

['entity', 'code', 'year', 'life_expectancy_0']

In [13]:
df.rename(columns={"entity": "Pais"}, inplace=True)

In [14]:
df.head()

          Pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [16]:
df.set_index(["Pais"])

            code  year  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [27]:
df_1=df.loc[df["code"].notnull(),["Pais","year","life_expectancy_0"]].head(3)
df_1

          Pais  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [28]:
df_1.shape

(3, 3)

In [30]:
df.dropna(subset=["code"], inplace=True)
#dropna borra las filas/columnas que coincidan con valores nulos dentro de "code", esto borra completamente del dataframe los valores.
df.isnull().sum()

Pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [31]:
df.shape

(20217, 4)

In [36]:
resultado = (
    df.groupby("Pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

resultado.head(5)

Pais
USSR            32.700000
South Sudan     37.841631
Sierra Leone    43.189605
Mali            43.760793
Niger           44.187513
Name: life_expectancy_0, dtype: float64

In [42]:
res_1 = df [(df["year"] >= 1970)]
res_1

              Pais code  year  life_expectancy_0
20     Afghanistan  AFG  1970            37.4601
21     Afghanistan  AFG  1971            37.9324
22     Afghanistan  AFG  1972            38.4226
23     Afghanistan  AFG  1973            38.9510
24     Afghanistan  AFG  1974            39.4687
...            ...  ...   ...                ...
21560     Zimbabwe  ZWE  2019            61.0603
21561     Zimbabwe  ZWE  2020            61.5300
21562     Zimbabwe  ZWE  2021            60.1347
21563     Zimbabwe  ZWE  2022            62.3601
21564     Zimbabwe  ZWE  2023            62.7748

[13284 rows x 4 columns]

In [43]:
resultado = (
    res_1.groupby("Pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

resultado.head(5)

Pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
Name: life_expectancy_0, dtype: float64